#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'pageCount' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER n
#  2. INTEGER p
#

def pageCount(n, p):
    # Write your code here
    if p <= n/2 :
        
        pc= int(p/2) 
    elif p==n:
        pc=0
    else:  
        if n%2!=0:
            pc= int((n-p)/2)
        else:
            if p%2==0:
                pc=int((n-p)/2)
            else:
                pc=int((n-p)/2) +1
    
    return pc
    

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    p = int(input().strip())

    result = pageCount(n, p)

    fptr.write(str(result) + '\n')

    fptr.close()
